"""Create guest book post table

Revision ID: 441cd65859e5
Revises: 
Create Date: 2019-12-29 20:10:08.408859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441cd65859e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('post_md', sa.Text(), nullable=False),
    sa.Column('post_html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('post_html'),
    sa.UniqueConstraint('post_md')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_book_post')
    # ### end Alembic commands ###
