"""revised table name to be plural

Revision ID: bec909f34ced
Revises: 441cd65859e5
Create Date: 2019-12-30 13:38:00.708694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec909f34ced'
down_revision = '441cd65859e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('post_md', sa.Text(), nullable=False),
    sa.Column('post_html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('post_html'),
    sa.UniqueConstraint('post_md')
    )
    op.drop_table('guest_book_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('posted_at', sa.DATETIME(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('post_md', sa.TEXT(), nullable=False),
    sa.Column('post_html', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('post_html'),
    sa.UniqueConstraint('post_md')
    )
    op.drop_table('guest_book_posts')
    # ### end Alembic commands ###
